# Generated by Django 4.0.4 on 2022-11-02 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id_hotel', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID HOTEL')),
                ('nombre_hotel', models.CharField(max_length=20, verbose_name='NOMBRE HOTEL')),
                ('direccion', models.CharField(max_length=30, verbose_name='DIRECCION')),
                ('telefono_hotel', models.IntegerField(verbose_name='TELEFONO')),
                ('mail_hotel', models.EmailField(max_length=254, verbose_name='MAIL')),
                ('cantidad_habitaciones', models.IntegerField(verbose_name='CANTIDAD HABITACIONES')),
                ('comuna', models.CharField(max_length=30, verbose_name='COMUNA')),
                ('region', models.CharField(max_length=30, verbose_name='REGION')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_habitacion',
            fields=[
                ('id_tipo', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID TIPO HABITACION')),
                ('descripcion_tipo', models.TextField(verbose_name='DESCRIPCION TIPO')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_servicio',
            fields=[
                ('id_tipo_servicio', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID TIPO SERVICIO')),
                ('descripcion_tipo', models.TextField(verbose_name='DESCRIPCION TIPO SERVICIO')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID SERVICIO')),
                ('nombre_servicio', models.CharField(max_length=30, verbose_name='NOMBRE SERVICIO')),
                ('descripcion_servicio', models.TextField(verbose_name='DESCRIPCION SERVICIO')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hotel')),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipo_servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id_habitacion', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID HABITACION')),
                ('nombre_habitacion', models.CharField(max_length=30, verbose_name='NOMBRE HABITACION')),
                ('descripcion_habitacion', models.TextField(verbose_name='DESCRIPCION HABITACION')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hotel')),
                ('tipo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipo_habitacion')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False, verbose_name='RUT ADMINISTRADOR')),
                ('dv_rut', models.IntegerField(verbose_name='DIGITO VERIFICADOR')),
                ('nombre_completo', models.CharField(max_length=40, verbose_name='NOMBRE COMPLETO')),
                ('telefono', models.IntegerField(verbose_name='TELEFONO')),
                ('mail', models.EmailField(max_length=254, verbose_name='MAIL')),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.hotel')),
            ],
        ),
    ]
