# Generated by Django 4.0.4 on 2022-11-07 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=40, verbose_name='NOMBRE COMPLETO')),
                ('rut', models.IntegerField(verbose_name='RUT')),
                ('dv_rut', models.IntegerField(verbose_name='DIGITO VERIFICADOR')),
                ('correo', models.EmailField(max_length=254, verbose_name='MAIL')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=40, verbose_name='NOMBRE COMPLETO')),
                ('rut', models.IntegerField(verbose_name='RUT')),
                ('dv_rut', models.IntegerField(verbose_name='DIGITO VERIFICADOR')),
                ('correo', models.EmailField(max_length=254, verbose_name='MAIL')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=30, verbose_name='NOMBRE SERVICIO')),
                ('tipo', models.CharField(max_length=30, null=True, verbose_name='TIPO')),
                ('precio', models.IntegerField(null=True, verbose_name='PRECIO')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='USUARIO', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='FECHA')),
                ('hora', models.IntegerField(choices=[[0, '8:00hrs. - 8:59hrs.'], [1, '9:00hrs. - 9:59hrs.'], [2, '10:00hrs. - 10:59hrs.'], [3, '11:00hrs. - 11:59hrs.'], [4, '12:00hrs. - 12:59hrs.'], [5, '13:00hrs. - 13:59hrs.'], [6, '14:00hrs. - 14:59hrs.']], verbose_name='HORA')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.servicio', verbose_name='SERVICIO')),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=30, verbose_name='USUARIO')),
                ('correo', models.EmailField(max_length=254, verbose_name='MAIL')),
                ('password', models.CharField(max_length=20, verbose_name='PASSWORD')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
    ]
