# Generated by Django 4.0.4 on 2022-11-07 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='hora',
            new_name='horas',
        ),
    ]
