# Generated by Django 4.0.4 on 2022-11-05 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente_cuenta_reserva_remove_habitacion_hotel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID EMPLEADO')),
                ('nombre_completo', models.CharField(max_length=40, verbose_name='NOMBRE COMPLETO')),
                ('rut', models.IntegerField(verbose_name='RUT')),
                ('dv_rut', models.IntegerField(verbose_name='DIGITO VERIFICADOR')),
                ('correo', models.EmailField(max_length=254, verbose_name='MAIL')),
            ],
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cuenta'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empleado'),
        ),
    ]
