# Generated by Django 4.0.4 on 2022-11-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empleado_alter_cuenta_cliente_alter_reserva_cuenta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='FECHA'),
        ),
    ]
